// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFPL.Data;

namespace NFPL.Migrations
{
    [DbContext(typeof(DbContextApp))]
    [Migration("20201015180449_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NFPL.Models.Conference", b =>
                {
                    b.Property<string>("ConferenceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConferenceID");

                    b.ToTable("Conferences");

                    b.HasData(
                        new
                        {
                            ConferenceID = "afc",
                            Name = "AFC"
                        },
                        new
                        {
                            ConferenceID = "nfc",
                            Name = "NFC"
                        });
                });

            modelBuilder.Entity("NFPL.Models.Division", b =>
                {
                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisionID");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            DivisionID = "north",
                            Name = "North"
                        },
                        new
                        {
                            DivisionID = "south",
                            Name = "South"
                        },
                        new
                        {
                            DivisionID = "east",
                            Name = "East"
                        },
                        new
                        {
                            DivisionID = "west",
                            Name = "West"
                        });
                });

            modelBuilder.Entity("NFPL.Models.Team", b =>
                {
                    b.Property<string>("TeamID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConferenceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamLogo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("ConferenceID");

                    b.HasIndex("DivisionID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = "ari",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Arizona Cardinals",
                            TeamLogo = "ARI.png"
                        },
                        new
                        {
                            TeamID = "atl",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Atlanta Falcons",
                            TeamLogo = "ATL.png"
                        },
                        new
                        {
                            TeamID = "bal",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Baltimore Ravens",
                            TeamLogo = "BAL.png"
                        },
                        new
                        {
                            TeamID = "buf",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "Buffalo Bills",
                            TeamLogo = "BUF.png"
                        },
                        new
                        {
                            TeamID = "car",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Carolina Panthers",
                            TeamLogo = "CAR.png"
                        },
                        new
                        {
                            TeamID = "chi",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Chicago Bears",
                            TeamLogo = "CHI.png"
                        },
                        new
                        {
                            TeamID = "cin",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Cincinnati Bengals",
                            TeamLogo = "CIN.png"
                        },
                        new
                        {
                            TeamID = "cle",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Cleveland Browns",
                            TeamLogo = "CLE.png"
                        },
                        new
                        {
                            TeamID = "dal",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Dallas Cowboys",
                            TeamLogo = "DAL.png"
                        },
                        new
                        {
                            TeamID = "den",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Denver Broncos",
                            TeamLogo = "DEN.png"
                        },
                        new
                        {
                            TeamID = "det",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Detroit Lions",
                            TeamLogo = "DET.png"
                        },
                        new
                        {
                            TeamID = "gb",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Green Bay Packers",
                            TeamLogo = "GB.png"
                        },
                        new
                        {
                            TeamID = "hou",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Houston Texans",
                            TeamLogo = "HOU.png"
                        },
                        new
                        {
                            TeamID = "ind",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Indianapolis Colts",
                            TeamLogo = "IND.png"
                        },
                        new
                        {
                            TeamID = "jax",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Jacksonville Jaguars",
                            TeamLogo = "JAX.png"
                        },
                        new
                        {
                            TeamID = "kc",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Kansas City Chiefs",
                            TeamLogo = "KC.png"
                        },
                        new
                        {
                            TeamID = "lac",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Los Angeles Chargers",
                            TeamLogo = "LAC.png"
                        },
                        new
                        {
                            TeamID = "lar",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Los Angeles Rams",
                            TeamLogo = "LAR.png"
                        },
                        new
                        {
                            TeamID = "mia",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "Miami Dolphins",
                            TeamLogo = "MIA.png"
                        },
                        new
                        {
                            TeamID = "min",
                            ConferenceID = "nfc",
                            DivisionID = "north",
                            Name = "Minnesota Vikings",
                            TeamLogo = "MIN.png"
                        },
                        new
                        {
                            TeamID = "ne",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "New England Patriots",
                            TeamLogo = "NE.png"
                        },
                        new
                        {
                            TeamID = "no",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "New Orleans Saints",
                            TeamLogo = "NO.png"
                        },
                        new
                        {
                            TeamID = "nyg",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "New York Giants",
                            TeamLogo = "NYG.png"
                        },
                        new
                        {
                            TeamID = "nyj",
                            ConferenceID = "afc",
                            DivisionID = "east",
                            Name = "New York Jets",
                            TeamLogo = "NYJ.png"
                        },
                        new
                        {
                            TeamID = "oak",
                            ConferenceID = "afc",
                            DivisionID = "west",
                            Name = "Oakland Raiders",
                            TeamLogo = "OAK.png"
                        },
                        new
                        {
                            TeamID = "phi",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Philadelphia Eagles",
                            TeamLogo = "PHI.png"
                        },
                        new
                        {
                            TeamID = "pit",
                            ConferenceID = "afc",
                            DivisionID = "north",
                            Name = "Pittsburgh Steelers",
                            TeamLogo = "PIT.png"
                        },
                        new
                        {
                            TeamID = "sea",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "Seattle Seahawks",
                            TeamLogo = "SEA.png"
                        },
                        new
                        {
                            TeamID = "sf",
                            ConferenceID = "nfc",
                            DivisionID = "west",
                            Name = "San Francisco 49ers",
                            TeamLogo = "SF.png"
                        },
                        new
                        {
                            TeamID = "tb",
                            ConferenceID = "nfc",
                            DivisionID = "south",
                            Name = "Tampa Bay Buccaneers",
                            TeamLogo = "TB.png"
                        },
                        new
                        {
                            TeamID = "ten",
                            ConferenceID = "afc",
                            DivisionID = "south",
                            Name = "Tennessee Titans",
                            TeamLogo = "TEN.png"
                        },
                        new
                        {
                            TeamID = "was",
                            ConferenceID = "nfc",
                            DivisionID = "east",
                            Name = "Washington Redskins",
                            TeamLogo = "WAS.png"
                        });
                });

            modelBuilder.Entity("NFPL.Models.Team", b =>
                {
                    b.HasOne("NFPL.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceID");

                    b.HasOne("NFPL.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID");
                });
#pragma warning restore 612, 618
        }
    }
}
